name: about_australia
description: A project for information about Australia 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.0.6
  concentric_transition: ^0.1.1
  google_sign_in: ^4.1.4
  intl: ^0.16.1
  flare_flutter: ^2.0.1
  transparent_image: ^1.0.0
  time_machine: ^0.9.12
  flutter_slidable: ^0.5.4
  characters: ^1.0.0
  flutter_localizations:
    sdk: flutter
  animations: ^1.1.2
  font_awesome_flutter: 8.11.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
  flutter_secure_storage: ^3.3.5
  firebase_database: ^4.4.0
  scrollable_positioned_list: ^0.1.8
  sticky_headers: ^0.1.8+1







  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  onboarding: ^1.0.5
  flutter_overboard: ^1.1.5
  introduction_screen: ^1.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Black.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Bold.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-ExtraBold.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-ExtraLight.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Light.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Medium.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Regular.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-SemiBold.ttf
        - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Thin.ttf
    - family: AustraliaIcons
      fonts:
        - asset: assets/icons/AustraliaIcons.ttf
    - family: Madani
      fonts:
        - asset: assets/fonts/Madani-Arabic-Black.ttf
        - asset: assets/fonts/Madani-Arabic-Bold.ttf
        - asset: assets/fonts/Madani-Arabic-Extra-Bold.ttf
        - asset: assets/fonts/Madani-Arabic-Extra-light.ttf
        - asset: assets/fonts/Madani-Arabic-light.ttf
        - asset: assets/fonts/Madani-Arabic-Medium.ttf
        - asset: assets/fonts/Madani-Arabic-Regular.ttf
        - asset: assets/fonts/Madani-Arabic-Semi-Bold.ttf
        - asset: assets/fonts/Madani-Arabic-Thin.ttf
        - asset: assets/fonts/Madani-Arabic-Variable.ttf




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/about_australia/
    - assets/images/map/
    - assets/images/travel/
    - assets/images/backgrounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
