/// Flutter icons AustraliaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AustraliaIcons
///      fonts:
///       - asset: fonts/AustraliaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AustraliaIcons {
  AustraliaIcons._();

  static const _kFontFam = 'AustraliaIcons';
  static const _kFontPkg = null;

  static const IconData history2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interview = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parchment = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplane = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ancient_scroll = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData australia = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData australia2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData australian_koala = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData canberra = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conversation = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_black = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
